//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Outfit
    {
        public int OutfitID { get; set; }
        [Display(Name = "Outfit Name")]
        public string OutfitName { get; set; }
        [Display(Name = "Item Name")]
        public int ItemID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
